platform :ios, '13.0'
use_frameworks!

target 'Runner' do
  # Pods for Runner
  pod 'SSZipArchive'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
